spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}704c8ca97ffa3f0d3b62ecb197ecf4429136bb8563977d055207d65614f1eed8'

token:
  expiration_time: 86400000
  secret: user_token_default

gateway:
  ip: 127.0.0.1