spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQBrhpQpbB46uJEZ12UcfvPDiemshs4WykDc2MRMdNBxetIxxLlEMngEgzonPTUbLIQViFzIlvzFsX8LaD548+em+lDGtXpczwgtwFV7snHj1EtR2ubUOoQPraZQrvPpmdlwNNA5fen37dRLFzK6k2NkB7taf7K2lgfY6zJzy7RlDgc2XFEvgKpUcyRXhd+fBmxaBVB3FRFdQObQUiAjAvAjeYdiHe2VCS1+S9mUBvHbrG3uBaTlo2GRtPclMMhujObV5197CUQo9ersD4P+/QGtFq0cDTKlFcRqtzTZ90OiQ6BErN7eOBKLeK9HlZdnwWH4XdGPxJP9uokBuwNVr2MGp7Yemu+btRQNmmqP7Eh+CEb5JtWaVKSZnpWuyg/nWuI='

order_service:
  url: http://127.0.0.1:8000/order-service/%s/orders

token:
  expiration_time: 86400000
  secret: user_token_default

gateway:
  ip: 127.0.0.1